# Generated by Django 4.1.dev20220504101500 on 2022-05-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_lessons_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='institution',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
