# Generated by Django 4.1.dev20220504101500 on 2022-05-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_delete_institution_remove_course_course_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
