# Generated by Django 4.1.dev20220504101500 on 2022-05-26 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0006_remove_course_students_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_learner',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='CourseLearner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.course_learner'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
