# Generated by Django 4.1.dev20220504101500 on 2022-05-20 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_lesson_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.section'),
            preserve_default=False,
        ),
    ]
