# Generated by Django 4.1.dev20220504101500 on 2022-05-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_remove_course_video_remove_course_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='lessons',
        ),
    ]
