# Generated by Django 4.1.dev20220504101500 on 2022-05-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_remove_section_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.section'),
            preserve_default=False,
        ),
    ]
