# Generated by Django 4.1.dev20220504101500 on 2022-05-12 11:04

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_description', models.TextField(blank=sqlalchemy.sql.expression.true, null=True)),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
            ],
        ),
    ]
