# Generated by Django 4.1.dev20220504101500 on 2022-05-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
