# Generated by Django 4.1.dev20220504101500 on 2022-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
