# Generated by Django 4.1.dev20220504101500 on 2022-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/%y'),
        ),
    ]
